# Generated by Django 3.2.23 on 2025-03-29 13:17

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publisher_name', models.CharField(max_length=30)),
                ('slug', models.SlugField(default='', max_length=70, unique=True)),
                ('popularity', models.CharField(choices=[('low', 'низкийй'), ('medium', 'средни'), ('high', 'высокий')], default='low', max_length=6)),
                ('publisher_content', models.TextField(default='text')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=100)),
                ('slug', models.SlugField(default='', max_length=70, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='имя автора')),
                ('last_name', models.CharField(max_length=30, verbose_name='фамилие автора')),
                ('photo_author', models.FileField(blank=True, null=True, upload_to='photo_author', verbose_name='фото автора')),
                ('slug', models.SlugField(default='', max_length=70, unique=True, verbose_name='слаг')),
                ('publisher', models.ManyToManyField(related_name='author', to='sait_app.Publisher')),
                ('tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author', to='sait_app.tag')),
            ],
            options={
                'verbose_name': 'писатель',
                'verbose_name_plural': 'писатели',
                'db_table': 'fast_app1_author',
                'ordering': ['-pk'],
                'default_related_name': 'author',
                'base_manager_name': 'objects_authormanager',
            },
            managers=[
                ('objects_authormanager', django.db.models.manager.Manager()),
            ],
        ),
    ]
