# Generated by Django 3.2.23 on 2025-03-29 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sait_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='author',
            table='sait_app_author',
        ),
    ]
